version: '3'

services:
  python-env:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ./output:/app/output
      - ./extras:/app/extras
    # command: /app/venv/bin/ipython
    ports:
      - 8888:8888

  postgres-db:
    image: postgres:13
    environment:
      # POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: churn
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "churn"]
      interval: 5s
      retries: 3
    restart: always
    ports:
      - 5432:5432 # allowing host to connect to backend db, for dev only

volumes:
  postgres-db-volume:
